"""
app/schemas/ws.py
------------------
Pydantic models for the /ws/agent WebSocket message protocol.

Client → Server
---------------
1. Auth frame (first frame on connect):
   { "type": "auth", "token": "<token>" }

2. Ping frame:
   { "type": "message", "requestType": "ping", "transactionId": "<id>", "payload": {} }

Server → Client
---------------
{ "type": "pong" | "error", "transactionId": "<id>", "content": "...", "timestamp": 1234567890 }
"""

from __future__ import annotations

import time
from typing import Any, Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Client → Server
# ---------------------------------------------------------------------------

class WSAuthFrame(BaseModel):
    """First frame after WS connect — must arrive before any other messages."""

    type: Literal["auth"]
    token: str


class WSClientMessage(BaseModel):
    """Client message frame."""

    type: Literal["message"] = "message"
    requestType: Literal["ping"] = "ping"
    transactionId: str = Field(description="Transaction ID generated by the client.")
    payload: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Server → Client
# ---------------------------------------------------------------------------

class WSServerMessage(BaseModel):
    """Outbound frame from server to client."""

    type: Literal["pong", "error"]
    transactionId: str
    content: str = ""
    timestamp: int = Field(default_factory=lambda: int(time.time()))

    def to_json(self) -> str:
        return self.model_dump_json()