import type { DatasetMetadata } from '../types';

export const DEFAULT_DEMO_DATASETS: DatasetMetadata[] = [
  {
    name: 'invoice.sql',
    tableName: 'invoice',
    rows: 412,
    columns: ['invoice_id', 'customer_id', 'invoice_date', 'billing_address', 'billing_city', 'billing_country', 'total'],
    description: 'Customer order transactions, billing info, and purchase totals.',
    useCase: 'Revenue trends, sales analytics, basket analysis',
    domainTags: ['Finance', 'Orders'],
  },
  {
    name: 'customer.sql',
    tableName: 'customer',
    rows: 59,
    columns: ['customer_id', 'first_name', 'last_name', 'company', 'address', 'city', 'country', 'email', 'support_rep_id'],
    description: 'Registered customer profiles and contact details.',
    useCase: 'Demographics, segmentation, customer LTV',
    domainTags: ['CRM', 'User Data'],
  },
  {
    name: 'track.sql',
    tableName: 'track',
    rows: 3503,
    columns: ['track_id', 'name', 'album_id', 'media_type_id', 'genre_id', 'composer', 'milliseconds', 'bytes', 'unit_price'],
    description: 'Catalog of music tracks with duration, pricing, and genre links.',
    useCase: 'Catalog analytics, track popularity',
    domainTags: ['Media', 'Catalog'],
  },
  {
    name: 'album.sql',
    tableName: 'album',
    rows: 347,
    columns: ['album_id', 'title', 'artist_id'],
    description: 'Music album details linked to performing artists.',
    useCase: 'Catalog mapping, artist portfolio',
    domainTags: ['Media'],
  },
  {
    name: 'artist.sql',
    tableName: 'artist',
    rows: 275,
    columns: ['artist_id', 'name'],
    description: 'Music performers, bands, and solo artists.',
    useCase: 'Artist performance & sales attribution',
    domainTags: ['Media'],
  },
  {
    name: 'genre.sql',
    tableName: 'genre',
    rows: 25,
    columns: ['genre_id', 'name'],
    description: 'Music genre classifications (Rock, Jazz, Metal, etc.).',
    useCase: 'Category performance breakdown',
    domainTags: ['Taxonomy'],
  },
  {
    name: 'employee.sql',
    tableName: 'employee',
    rows: 8,
    columns: ['employee_id', 'last_name', 'first_name', 'title', 'reports_to', 'birth_date', 'hire_date', 'city'],
    description: 'Internal staff profiles and support representatives.',
    useCase: 'Employee sales support attribution',
    domainTags: ['HR'],
  },
  {
    name: 'invoice_line.sql',
    tableName: 'invoice_line',
    rows: 2240,
    columns: ['invoice_line_id', 'invoice_id', 'track_id', 'unit_price', 'quantity'],
    description: 'Individual line items of tracks purchased per invoice.',
    useCase: 'Cross-selling, itemized sales breakdown',
    domainTags: ['Orders', 'Items'],
  },
  {
    name: 'media_type.sql',
    tableName: 'media_type',
    rows: 5,
    columns: ['media_type_id', 'name'],
    description: 'Audio formats (AAC, MPEG, FLAC, etc.).',
    useCase: 'Format consumption trends',
    domainTags: ['Technical'],
  },
];

export const INITIAL_DEMO_PROJECT = {
  id: 'demo-project',
  title: 'Music E-commerce (Demo)',
  name: 'Music E-commerce (Demo)',
  description: 'Pre-loaded Music E-commerce dataset with 9 tables — query sales, tracks, customers, and more.',
  is_demo: true,
  isDemo: true,
  datasets: DEFAULT_DEMO_DATASETS,
  datasetsCount: DEFAULT_DEMO_DATASETS.length,
  session_id: 'demo-session',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  messages: [],
};
